yolo_model:

  config_file:
    name: icy_yolov4.cfg
  weight_file:
    name: icy_yolov4_turtle.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - targetA
      - targetB 
      - targetC
      - targetD
      - targetE
